// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbmgtPO13QqzCSwK22qs_WTfXTvxIljU',
    appId: '1:981400631776:web:6ae3c27c46a57ce1dd9385',
    messagingSenderId: '981400631776',
    projectId: 'evoltsoft',
    authDomain: 'evoltsoft.firebaseapp.com',
    storageBucket: 'evoltsoft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TUEXi9BhBBcckfZ5kAio9SkldShytVc',
    appId: '1:981400631776:android:4f2b00cc67894afddd9385',
    messagingSenderId: '981400631776',
    projectId: 'evoltsoft',
    storageBucket: 'evoltsoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfu-OC3t8cSI8PUIauJkU7hMyYLoq9Dg',
    appId: '1:981400631776:ios:44b7ee9b0c4d6919dd9385',
    messagingSenderId: '981400631776',
    projectId: 'evoltsoft',
    storageBucket: 'evoltsoft.appspot.com',
    iosBundleId: 'com.example.evoltsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfu-OC3t8cSI8PUIauJkU7hMyYLoq9Dg',
    appId: '1:981400631776:ios:44b7ee9b0c4d6919dd9385',
    messagingSenderId: '981400631776',
    projectId: 'evoltsoft',
    storageBucket: 'evoltsoft.appspot.com',
    iosBundleId: 'com.example.evoltsoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHbmgtPO13QqzCSwK22qs_WTfXTvxIljU',
    appId: '1:981400631776:web:43d52dd06f405cf1dd9385',
    messagingSenderId: '981400631776',
    projectId: 'evoltsoft',
    authDomain: 'evoltsoft.firebaseapp.com',
    storageBucket: 'evoltsoft.appspot.com',
  );
}
